#sudo: false # use container based infrastructure
sudo: required # use docker

services:
  - docker

env: 
  global:
    - secure: "Tp1WwUlfjjwsAzz+S1I6LMtMhkzKGfY3TgsiPEsOMRilFoIFcJZvfEXgZFvzLUfu4qyC/3uKNwI9I6ZPRGBDlqaIuwgkutJRGSaf4yJwBMBFuqNl4FOhgkcysc0LEWcwujEGSqKU3xXgBtxLqn+xjXfQfm4WxVa03ce4jeBRQ7ZifDEm/1t2TVf7x/YBecyGdCzJIUefffxbbE1lPqsgeIFRw5fZQFdSeX4o0jFzY42o+jbZo47OBYoRCfFN8D3I5iHwWni1alXaImQ20ODgmU23wfam5yBASR5sCWtbS34nP/0jtffu/FugnVqVgLGfgFs4Ywc3kJ/ptjOaNZqiWQB6nWBSIgaukpIATwcbc6v6CnnaCEEYjj9M7WS9jWpD3PdOUnpzx8MItcfRCZHahzkbOTDtbDuJRZschWRMwUXpDEjG1SYG950IBq1dFCvecfHNCdbNkNQef6cYrq4VlkYGLr3ZPsQ+fHtG0s4JUOebLiyixYnajs3sTM+ihzawkc+Ov9JmK9jQj5F4PpeXCO0pNYBWpHvhi/ZlZaqwCZqCkLKNGdoi7ziviyD0P6kBg935MDJBXrsaGvzD4oUz2WNHjyPJwk+rXhbx5iC/+XkMkluYCLGdX2b0+QMyxexgCa7SDPl1A5rPTn1hIGs/HKaz3GxQvJoQf2eIA6Q9L0Y="

language: node_js

node_js:
  - 0.12

before_script:
  - npm install -g gulp

script:
  - gulp package
  - echo we are done 

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh gh-pages
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "feature/GL-36-dist" && bash deploy.sh gh-pages-test

before_install:
  - docker build -t blecherat/gitline .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push blecherat/gitline
